version: '3.8'

services:
  stock-price-prediction-bot:
    image: stock-price-prediction-bot
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    command: ["java", "-jar", "stock-price-prediction-bot.jar"]

  stock-price-prediction-app:
    image: stock-price-prediction-app
    ports:
      - "5000:5000"
    command: ["python", "app.py"]