spring:
  application:
    name: stock-price-prediction-bot
  config:
    import: classpath:hidden.yml

stock-price-prediction-bot:
  name: StockPricePredictionBot
  video-path: src/main/resources/videos
  app:
    base-url: http://localhost:5000