spring:
  application:
    name: stock-price-prediction-bot
  config:
    import: classpath:hidden.yml

stock-price-prediction-bot:
  name: MITStockPricePredictionBot
  video-path: /home/${stock-price-prediction-bot.user}/resources/videos
  app:
    base-url: http://stock-price-prediction-app:5000